# Generated by Django 5.2.6 on 2026-09-21 17:50

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artist_name", models.CharField(max_length=150)),
                ("stage_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=30, validators=[core.utils.validate_bd_phone]
                    ),
                ),
                ("art_form", models.CharField(max_length=100)),
                ("experience", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        upload_to="applications/artists/%Y/%m/",
                        validators=[core.utils.validate_image_upload],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[core.utils.validate_bd_phone],
                    ),
                ),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("guests", models.PositiveIntegerField(blank=True, null=True)),
                ("budget", models.CharField(blank=True, max_length=80)),
                ("venue", models.CharField(blank=True, max_length=150)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("experience", models.CharField(blank=True, max_length=80)),
                ("salary", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="TalentHuntRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=30, validators=[core.utils.validate_bd_phone]
                    ),
                ),
                ("talent_category", models.CharField(max_length=100)),
                ("experience", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("social_media", models.URLField(blank=True)),
                ("portfolio_link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shortlisted", "Shortlisted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=30, validators=[core.utils.validate_bd_phone]
                    ),
                ),
                ("service_category", models.CharField(max_length=120)),
                ("experience", models.CharField(blank=True, max_length=100)),
                ("business_address", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("account_number", models.CharField(blank=True, max_length=60)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        upload_to="vendors/documents/%Y/%m/",
                        validators=[core.utils.validate_doc_upload],
                    ),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtistBookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artist_name", models.CharField(blank=True, max_length=150)),
                ("artist_category", models.CharField(blank=True, max_length=30)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=30, validators=[core.utils.validate_bd_phone]
                    ),
                ),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("budget", models.CharField(blank=True, max_length=80)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Which form sent it (query-modal, book-an-artist…)",
                        max_length=40,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_requests",
                        to="artists.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=30, validators=[core.utils.validate_bd_phone]
                    ),
                ),
                ("experience", models.CharField(blank=True, max_length=100)),
                ("skills", models.CharField(blank=True, max_length=300)),
                ("cover_letter", models.TextField(blank=True)),
                ("expected_salary", models.CharField(blank=True, max_length=80)),
                ("join_date", models.CharField(blank=True, max_length=60)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        upload_to="applications/jobs/%Y/%m/",
                        validators=[core.utils.validate_doc_upload],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("shortlisted", "Shortlisted"),
                            ("interviewed", "Interviewed"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="engagement.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
