# Generated by Django 5.2.6 on 2026-09-21 17:50

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InfluencerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Niche, e.g. 'Fashion'", max_length=100
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=600)),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        upload_to="influencers/%Y/%m/",
                        validators=[core.utils.validate_image_upload],
                    ),
                ),
                ("followers", models.CharField(blank=True, max_length=60)),
                (
                    "engagement",
                    models.CharField(
                        blank=True, help_text="e.g. '4.2%'", max_length=30
                    ),
                ),
                ("posts", models.CharField(blank=True, max_length=30)),
                ("platforms", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("avg_reach", models.CharField(blank=True, max_length=80)),
                ("price", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TalentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(db_index=True, max_length=100)),
                (
                    "image",
                    models.CharField(
                        blank=True, help_text="URL or emoji", max_length=300
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=4.5,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("experience", models.CharField(blank=True, max_length=80)),
                ("bio", models.TextField(blank=True)),
                ("full_bio", models.TextField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("audio_url", models.URLField(blank=True)),
                ("portfolio", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("rates", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("singer", "Singer"),
                            ("dj", "DJ"),
                            ("comedian", "Comedian"),
                            ("magician", "Magician"),
                            ("dancer", "Dancer"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=600)),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        upload_to="artists/%Y/%m/",
                        validators=[core.utils.validate_image_upload],
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=4.5,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="Display price, e.g. '৳8,00,000'",
                        max_length=80,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Short card description"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Longer bio for detail views"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, help_text="e.g. 'Pop, Romantic'", max_length=200
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        help_text="Display text, e.g. '20+ years'",
                        max_length=80,
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("popular_songs", models.JSONField(blank=True, default=list)),
                ("specialties", models.JSONField(blank=True, default=list)),
                ("awards", models.JSONField(blank=True, default=list)),
                (
                    "styles",
                    models.JSONField(
                        blank=True, default=list, help_text="Dance styles"
                    ),
                ),
                (
                    "social_media",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{facebook, instagram, youtube, twitter}",
                    ),
                ),
                (
                    "availability",
                    models.CharField(blank=True, default="Available", max_length=60),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[core.utils.validate_bd_phone],
                    ),
                ),
                ("famous_show", models.CharField(blank=True, max_length=200)),
                ("famous_for", models.CharField(blank=True, max_length=250)),
                ("media_presence", models.CharField(blank=True, max_length=200)),
                (
                    "followers",
                    models.CharField(
                        blank=True, help_text="Display text, e.g. '2.5M'", max_length=60
                    ),
                ),
                (
                    "tour_status",
                    models.CharField(blank=True, default="Active", max_length=60),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"],
                        name="artists_art_categor_0374a4_idx",
                    )
                ],
            },
        ),
    ]
