# Generated by Django 5.2.6 on 2026-09-21 17:50

import core.utils
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("image", models.CharField(blank=True, max_length=600)),
                ("excerpt", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="HTML — sanitised server-side"
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=120)),
                (
                    "published_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("read_time", models.CharField(blank=True, max_length=40)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("featured", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("legacy_id", models.CharField(blank=True, max_length=220)),
            ],
            options={
                "ordering": ["-published_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("corporate", "Corporate"),
                            ("influencer", "Influencer"),
                        ],
                        db_index=True,
                        default="home",
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "image",
                    models.CharField(
                        help_text="Image URL or uploaded file", max_length=600
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        upload_to="gallery/%Y/%m/",
                        validators=[core.utils.validate_image_upload],
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "gallery images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("subtitle", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.CharField(
                        help_text="Absolute URL or uploaded image.", max_length=600
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        upload_to="hero/%Y/%m/",
                        validators=[core.utils.validate_image_upload],
                    ),
                ),
                (
                    "stats",
                    models.CharField(
                        blank=True,
                        help_text="Badge text, e.g. '500+ Events Planned'",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("image", models.CharField(blank=True, max_length=600)),
                ("gallery", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("client", models.CharField(blank=True, max_length=150)),
                (
                    "event_date",
                    models.CharField(
                        blank=True,
                        help_text="Display date, e.g. 'June 2023'",
                        max_length=60,
                    ),
                ),
                ("budget", models.CharField(blank=True, max_length=60)),
                ("video_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Display category label", max_length=80
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Emoji icon", max_length=16),
                ),
                ("short_description", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, max_length=600)),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="Display price, e.g. '৳50,000+'",
                        max_length=60,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Optional page link, e.g. /services/corporate-events",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(default="active", editable=False, max_length=20),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(default="Ananta Events", max_length=120),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("pinterest", models.URLField(blank=True)),
                ("about_text", models.TextField(blank=True)),
                ("footer_text", models.TextField(blank=True)),
                ("map_embed_url", models.URLField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("seo_description", models.TextField(blank=True)),
                ("og_image", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("image", models.CharField(blank=True, max_length=600)),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("social", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("designation", models.CharField(blank=True, max_length=150)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("image", models.CharField(blank=True, max_length=600)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.TextField()),
                ("event_type", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("youtube_id", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.CharField(blank=True, max_length=600)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unpublished items are hidden from all public endpoints.",
                        verbose_name="published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("corporate_event", "Corporate Event"),
                            ("exhibition_stall", "Exhibition Stall"),
                            ("photography_service", "Photography Service"),
                            ("special_event", "Special Event"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=120)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("featured", models.BooleanField(default=False)),
                ("cover_image", models.CharField(blank=True, max_length=600)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("included_services", models.JSONField(blank=True, default=list)),
                (
                    "stats",
                    models.JSONField(
                        blank=True, default=list, help_text="[{number, label}]"
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True,
                        help_text="Original frontend id/slug for redirect mapping",
                        max_length=220,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["entry_type", "is_published"],
                        name="content_ser_entry_t_1cd68f_idx",
                    )
                ],
            },
        ),
    ]
