# Generated by Django 5.2.6 on 2026-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_stats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="About page stats [{number, label, icon}]",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_values",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="About page core values [{icon, title, description}]",
            ),
        ),
    ]
