"""Serializers for every content model (shared by public and admin endpoints)."""

from __future__ import annotations

from rest_framework import serializers

from apps.common.validators import sanitize_html, validate_image_upload, validate_youtube_url
from apps.content.models import (
    FAQ,
    Artist,
    BlogPost,
    ContentBlock,
    Event,
    GalleryImage,
    HeroSlide,
    InfluencerProfile,
    JobPosting,
    PortfolioImage,
    PortfolioItem,
    Service,
    ServiceEntry,
    ServiceEntryImage,
    SiteSettings,
    TeamMember,
    Testimonial,
    Video,
)

IMAGE_SRC_HELP = "Resolved image URL (uploaded file if present, otherwise image_url)."


class AutoSlugMixin:
    """Slugs are generated by the model, so the API must not require them."""

    def get_extra_kwargs(self):
        kwargs = super().get_extra_kwargs()
        if (
            "slug" in getattr(self.Meta, "fields", [])
            or getattr(self.Meta, "fields", None) == "__all__"
        ):
            kwargs.setdefault("slug", {"required": False, "allow_blank": True, "allow_null": True})
        return kwargs


class ImageSrcMixin(AutoSlugMixin, serializers.ModelSerializer):
    image_src = serializers.CharField(read_only=True, help_text=IMAGE_SRC_HELP)

    def validate_image(self, value):
        if value:
            validate_image_upload(value)
        return value


class ImageSrcOnlyMixin(serializers.ModelSerializer):
    """For models without an upload field but with an external URL (`image_url`)."""


class SiteSettingsSerializer(serializers.ModelSerializer):
    class Meta:
        model = SiteSettings
        fields = "__all__"
        read_only_fields = ["updated_at"]


class HeroSlideSerializer(ImageSrcMixin):
    class Meta:
        model = HeroSlide
        fields = "__all__"


class ServiceEntryListSerializer(ImageSrcMixin):
    """Compact representation used inside the service detail payload."""

    class Meta:
        model = ServiceEntry
        fields = [
            "id",
            "slug",
            "title",
            "subtitle",
            "category",
            "summary",
            "image",
            "image_url",
            "image_src",
            "image_alt",
            "order",
            "is_published",
            "is_featured",
        ]


class ServiceEntryImageSerializer(ImageSrcMixin):
    class Meta:
        model = ServiceEntryImage
        fields = "__all__"


class ServiceEntrySerializer(ImageSrcMixin):
    gallery = ServiceEntryImageSerializer(source="images", many=True, read_only=True)
    service_name = serializers.CharField(source="service.name", read_only=True)
    service_slug = serializers.CharField(source="service.slug", read_only=True)

    class Meta:
        model = ServiceEntry
        fields = "__all__"
        # The slug is generated server-side, so DRF's auto-generated
        # UniqueTogetherValidator (service + slug) would wrongly demand it.
        validators = []

    def validate_body(self, value):
        return sanitize_html(value)


class ServiceListSerializer(ImageSrcMixin):
    entries_count = serializers.IntegerField(source="serviceentry_set.count", read_only=True)

    class Meta:
        model = Service
        fields = [
            "id",
            "slug",
            "name",
            "badge",
            "heading",
            "heading_highlight",
            "summary",
            "icon",
            "color_from",
            "color_to",
            "features",
            "image",
            "image_url",
            "image_src",
            "image_alt",
            "order",
            "is_published",
            "show_in_nav",
            "entries_count",
            "seo_title",
            "seo_description",
            "created_at",
            "updated_at",
        ]


class ServiceDetailSerializer(ServiceListSerializer):
    entries = serializers.SerializerMethodField()

    class Meta(ServiceListSerializer.Meta):
        fields = [*ServiceListSerializer.Meta.fields, "body", "entries"]

    def get_entries(self, obj) -> list:
        request = self.context.get("request")
        qs = obj.serviceentry_set.all()
        if not (request and getattr(request.user, "is_staff", False)):
            qs = qs.filter(is_published=True)
        qs = qs.order_by("order", "id")
        return ServiceEntryListSerializer(qs, many=True, context=self.context).data


class ServiceAdminSerializer(ServiceDetailSerializer):
    pass


class ArtistSerializer(ImageSrcMixin):
    category_display = serializers.CharField(source="get_category_display", read_only=True)
    youtube_embed = serializers.CharField(read_only=True)

    class Meta:
        model = Artist
        fields = "__all__"

    def validate_video_url(self, value):
        validate_youtube_url(value)
        return value


class InfluencerProfileSerializer(ImageSrcMixin):
    class Meta:
        model = InfluencerProfile
        fields = "__all__"


class ContentBlockSerializer(serializers.ModelSerializer):
    section_display = serializers.CharField(source="get_section_display", read_only=True)
    image_src = serializers.CharField(read_only=True)

    class Meta:
        model = ContentBlock
        fields = "__all__"


class PortfolioImageSerializer(ImageSrcMixin):
    class Meta:
        model = PortfolioImage
        fields = "__all__"


class PortfolioItemSerializer(ImageSrcMixin):
    images = PortfolioImageSerializer(many=True, read_only=True)

    class Meta:
        model = PortfolioItem
        fields = "__all__"

    def validate_video_url(self, value):
        validate_youtube_url(value)
        return value


class GalleryImageSerializer(ImageSrcMixin):
    class Meta:
        model = GalleryImage
        fields = "__all__"


class VideoSerializer(serializers.ModelSerializer):
    youtube_id = serializers.CharField(read_only=True)
    thumbnail_url = serializers.CharField(read_only=True)
    embed_url = serializers.CharField(read_only=True)

    class Meta:
        model = Video
        fields = "__all__"

    def validate_youtube_url(self, value):
        validate_youtube_url(value)
        return value


class BlogPostSerializer(ImageSrcMixin):
    author_display = serializers.SerializerMethodField()

    class Meta:
        model = BlogPost
        fields = "__all__"
        read_only_fields = ["views", "published_at", "author"]

    def get_author_display(self, obj) -> str:
        return obj.author_name or (obj.author.get_full_name() if obj.author_id else "Ananta Events")

    def validate_content(self, value):
        return sanitize_html(value)


class BlogPostListSerializer(BlogPostSerializer):
    class Meta(BlogPostSerializer.Meta):
        fields = [
            "id",
            "slug",
            "title",
            "category",
            "excerpt",
            "image",
            "image_url",
            "image_src",
            "image_alt",
            "author_name",
            "author_display",
            "tags",
            "is_featured",
            "is_published",
            "published_at",
            "read_minutes",
            "views",
            "created_at",
            "updated_at",
        ]


class TestimonialSerializer(ImageSrcMixin):
    class Meta:
        model = Testimonial
        fields = "__all__"


class TeamMemberSerializer(ImageSrcMixin):
    class Meta:
        model = TeamMember
        fields = "__all__"


class FAQSerializer(serializers.ModelSerializer):
    section_display = serializers.CharField(source="get_section_display", read_only=True)

    class Meta:
        model = FAQ
        fields = "__all__"


class JobPostingSerializer(AutoSlugMixin, serializers.ModelSerializer):
    is_open = serializers.BooleanField(read_only=True)
    employment_type_display = serializers.CharField(
        source="get_employment_type_display", read_only=True
    )
    application_count = serializers.IntegerField(source="applications.count", read_only=True)

    class Meta:
        model = JobPosting
        fields = "__all__"

    def validate_description(self, value):
        return sanitize_html(value)


class EventSerializer(ImageSrcMixin):
    status_display = serializers.CharField(source="get_status_display", read_only=True)
    attendee_count = serializers.IntegerField(read_only=True)
    is_upcoming = serializers.BooleanField(read_only=True)

    class Meta:
        model = Event
        fields = "__all__"
